### ISSUE TITLE
Analyse Werk

### ISSUE THREAD

**Issue by Jason2426** [Abeeryu/connect-your-tribe-squad-page#1]
**Wat is mooi?**
Het design is strak en mooi gemaakt met kleuren, de filter ziet er qua indeling erg logisch en goed bedacht uit.  

**Wat werkt goed?**
Qua functionaliteit werkt de filter erg goed en de code is ook dynamisch wat perfect is, dit zouden we zo kunnen gebruiken op de uiteindelijke squadpage. 

**Wat werkt niet zo goed**
Geen opmerkingen.

**Wat kan beter?**
Dit is nog geen opdracht voor een opdrachtgever, misschien que design iets wat je zelf super leuk of mooi vind bijvoorbeeld een muziek geinspireerde website of vette animaties toevoegen!

**Comment by Abeeryu** [comment]
Bedankt voor de feedback!

Ik heb het ontwerp snel gemaakt. Mijn focus point was op het functionaliteit, zeker ga ik later mijn ontwerp wat mooier maken :)
