### ISSUE TITLE
Feedback squadpage

### ISSUE THREAD

**Issue by Patrickkhr** [Abeeryu/connect-your-tribe-squad-page#2]
Wat is mooi, wat werkt goed?

Clean design, het is duidelijk wat je wilt laten zien en het word op een mooie manier weergegeven
cool filtersysteem en het werkt goed.

Wat kan beter, wat werkt niet zo goed?

Het design nog iets meer proberen toe te passen op je website.

**Comment by Abeeryu** [comment]
Bedankt voor de feedback!
Ik heb het ontwerp snel gemaakt. Mijn focus point was op het functionaliteit, zeker ga ik later mijn ontwerp wat mooier maken :)
