### ISSUE TITLE
Feedback squadpage

### ISSUE THREAD

**Issue by lisavanmansom** [Abeeryu/connect-your-tribe-squad-page#3]
Wat is mooi, wat werkt goed?

Het idee van schets is een clean en netjes design. Ook gaaf dat je filtersysteem al werkend is.

Wat kan beter, wat werkt niet zo goed?

Het design van je schets nog meer implementeren. Verder is het nog niet helemaal responsive.

**Comment by Abeeryu** [comment]
Bedankt voor de feedback!

Mijn focus point was op het functionaliteit, zeker ga ik later mijn ontwerp wat mooier en responsive maken :)
